/* Generated by the Systemtap dtrace wrapper */

#define _SDT_HAS_SEMAPHORES 1


#define STAP_HAS_SEMAPHORES 1 /* deprecated */


#include <sys/sdt.h>

/* WRAPPER_JS_OBJECT_GETATTR ( V8Object_t *obj, string_t name) */
#if defined STAP_SDT_V1
#define WRAPPER_JS_OBJECT_GETATTR_ENABLED() __builtin_expect (js__object__getattr_semaphore, 0)
#define wrapper_js__object__getattr_semaphore js__object__getattr_semaphore
#else
#define WRAPPER_JS_OBJECT_GETATTR_ENABLED() __builtin_expect (wrapper_js__object__getattr_semaphore, 0)
#endif
__extension__ extern unsigned short wrapper_js__object__getattr_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define WRAPPER_JS_OBJECT_GETATTR(arg1,arg2) \
DTRACE_PROBE2(wrapper,js__object__getattr,arg1,arg2)

/* WRAPPER_JS_OBJECT_SETATTR ( V8Object_t *obj, string_t name, PyObject_t *o) */
#if defined STAP_SDT_V1
#define WRAPPER_JS_OBJECT_SETATTR_ENABLED() __builtin_expect (js__object__setattr_semaphore, 0)
#define wrapper_js__object__setattr_semaphore js__object__setattr_semaphore
#else
#define WRAPPER_JS_OBJECT_SETATTR_ENABLED() __builtin_expect (wrapper_js__object__setattr_semaphore, 0)
#endif
__extension__ extern unsigned short wrapper_js__object__setattr_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define WRAPPER_JS_OBJECT_SETATTR(arg1,arg2,arg3) \
DTRACE_PROBE3(wrapper,js__object__setattr,arg1,arg2,arg3)

/* WRAPPER_JS_OBJECT_DELATTR ( V8Object_t *obj, string_t name) */
#if defined STAP_SDT_V1
#define WRAPPER_JS_OBJECT_DELATTR_ENABLED() __builtin_expect (js__object__delattr_semaphore, 0)
#define wrapper_js__object__delattr_semaphore js__object__delattr_semaphore
#else
#define WRAPPER_JS_OBJECT_DELATTR_ENABLED() __builtin_expect (wrapper_js__object__delattr_semaphore, 0)
#endif
__extension__ extern unsigned short wrapper_js__object__delattr_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define WRAPPER_JS_OBJECT_DELATTR(arg1,arg2) \
DTRACE_PROBE2(wrapper,js__object__delattr,arg1,arg2)

/* WRAPPER_JS_ARRAY_GETITEM ( V8Array_t *obj, PyObject_t *key) */
#if defined STAP_SDT_V1
#define WRAPPER_JS_ARRAY_GETITEM_ENABLED() __builtin_expect (js__array__getitem_semaphore, 0)
#define wrapper_js__array__getitem_semaphore js__array__getitem_semaphore
#else
#define WRAPPER_JS_ARRAY_GETITEM_ENABLED() __builtin_expect (wrapper_js__array__getitem_semaphore, 0)
#endif
__extension__ extern unsigned short wrapper_js__array__getitem_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define WRAPPER_JS_ARRAY_GETITEM(arg1,arg2) \
DTRACE_PROBE2(wrapper,js__array__getitem,arg1,arg2)

/* WRAPPER_JS_ARRAY_SETITEM ( V8Array_t *obj, PyObject_t *key, PyObject_t *value) */
#if defined STAP_SDT_V1
#define WRAPPER_JS_ARRAY_SETITEM_ENABLED() __builtin_expect (js__array__setitem_semaphore, 0)
#define wrapper_js__array__setitem_semaphore js__array__setitem_semaphore
#else
#define WRAPPER_JS_ARRAY_SETITEM_ENABLED() __builtin_expect (wrapper_js__array__setitem_semaphore, 0)
#endif
__extension__ extern unsigned short wrapper_js__array__setitem_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define WRAPPER_JS_ARRAY_SETITEM(arg1,arg2,arg3) \
DTRACE_PROBE3(wrapper,js__array__setitem,arg1,arg2,arg3)

/* WRAPPER_JS_ARRAY_DELITEM ( V8Array_t *obj, PyObject_t *key) */
#if defined STAP_SDT_V1
#define WRAPPER_JS_ARRAY_DELITEM_ENABLED() __builtin_expect (js__array__delitem_semaphore, 0)
#define wrapper_js__array__delitem_semaphore js__array__delitem_semaphore
#else
#define WRAPPER_JS_ARRAY_DELITEM_ENABLED() __builtin_expect (wrapper_js__array__delitem_semaphore, 0)
#endif
__extension__ extern unsigned short wrapper_js__array__delitem_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define WRAPPER_JS_ARRAY_DELITEM(arg1,arg2) \
DTRACE_PROBE2(wrapper,js__array__delitem,arg1,arg2)

/* ENGINE_SCRIPT_COMPILE ( V8Script_t *s, string_t source, string_t name, int line, int column) */
#if defined STAP_SDT_V1
#define ENGINE_SCRIPT_COMPILE_ENABLED() __builtin_expect (script__compile_semaphore, 0)
#define engine_script__compile_semaphore script__compile_semaphore
#else
#define ENGINE_SCRIPT_COMPILE_ENABLED() __builtin_expect (engine_script__compile_semaphore, 0)
#endif
__extension__ extern unsigned short engine_script__compile_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define ENGINE_SCRIPT_COMPILE(arg1,arg2,arg3,arg4,arg5) \
DTRACE_PROBE5(engine,script__compile,arg1,arg2,arg3,arg4,arg5)

/* ENGINE_SCRIPT_RUN ( V8Script_t *s) */
#if defined STAP_SDT_V1
#define ENGINE_SCRIPT_RUN_ENABLED() __builtin_expect (script__run_semaphore, 0)
#define engine_script__run_semaphore script__run_semaphore
#else
#define ENGINE_SCRIPT_RUN_ENABLED() __builtin_expect (engine_script__run_semaphore, 0)
#endif
__extension__ extern unsigned short engine_script__run_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define ENGINE_SCRIPT_RUN(arg1) \
DTRACE_PROBE1(engine,script__run,arg1)

